# fly.toml app configuration file generated for datingapp-101 on 2023-08-01T14:57:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapp-101"
primary_region = "atl"

[build]
  image = "nihtin/datingapp:1.0.21"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="du4jgcmme"
  CloudinarySettings__ApiKey="722664698332539"
  CloudinarySettings__ApiSecret="hqtYU2lAe-NlDOXMJ8vEga5Iywo"
  TokenKey="super secret unguessable key"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
